INSERT INTO `role` VALUES (1,'ROLE_ADMIN');
INSERT INTO `role` VALUES (2,'ROLE_USER');
INSERT INTO `role` VALUES (3,'ROLE_TEACHER');
INSERT INTO `role` VALUES (4,'ROLE_COORDINATOR');
INSERT INTO `role` VALUES (5,'ROLE_ACCOUNTANT');
INSERT INTO `role` VALUES (6,'ROLE_RECEPTIONIST');